name: angular-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Navigate to Angular project directory
      run: cd angularcrud-main
          
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
