name: ci/cd-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build .NET Backend
      run: |
        cd WEBAPIUPDATED\WebAPI
        dotnet publish -c Release -o published
        ls  # List contents to verify you are in the right directory
        echo "::set-output name=backend_path::WEBAPIUPDATED\WebAPI\published"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
          
    - name: Install Dependencies
      run: |
          cd angularcrud-main
          npm install

    - name: Build and Test Angular Frontend
      run: |
          cd angularcrud-main
          npm run build
          
    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-artifact
        path: WEBAPIUPDATED\WebAPI\published

    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-artifact
        path: AngularCRUD/dist

          
  deploy:
    needs: build
    runs-on: windows-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: WEBAPIUPDATED\WebAPI\published

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: AngularCRUD/dist

      - name: Copy file to IIS
        run: |
          #copy .net 
          cp -r WEBAPIUPDATED\WebAPI\published\* "D:\AngularWEBapi"

      - name: Copy Agular Frontend to IIS
        run: |
          cp -r AngularCRUD/dist/* "D:\AngularWEBapi"
