name: dotnet-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build Backend
      run: dotnet build --configuration Release ./WebAPI/WebAPI.sln

    - name: dotnet publish
      run: dotnet publish -c Release ./WebAPI/WebAPI.sln

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
          
    - name: Install Dependencies
      run: |
          cd angularcrud-main
          npm install

    - name: Build and Test Angular Frontend
      run: |
          cd angularcrud-main
          ng build --prod
